<div id="register">
	<div class="error">
		 
		<?php if(isset($error)):  ?>
			<?php if($error === 1): ?>
						<p>User already exist<p>
			<?php endif ?>
			<?php if($error === 2): ?>
						<p>Enter a login<p>
			<?php endif ?>
			<?php if($error === 3): ?>
						<p>Invalid password<p>
			<?php endif ?>
			<?php if($error === 4): ?>
						<p>Enter a password<p>
			<?php endif ?>
		<?php endif ?>
		
	</div>
	<h1>Create your account :</h1>
	<form method="POST">
		<input class="form-control" name="login" type="text" placeholder="Login">
		<input class="form-control" name="password" type="password" placeholder="Password">
		<input class="form-control" name="passwordVerif" type="password" placeholder="Confirm password">
		<input class="form-control" name="mail" type="mail" placeholder="Mail">
		<button name="action" value="register">Créer</button>
	</form>
</div>