<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>E-commerce</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet" href="public/css/normalize.css">
        <link rel="stylesheet" href="public/css/style.css">
        <script
              src="https://code.jquery.com/jquery-3.2.1.js"
              integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
              crossorigin="anonymous">
        </script>
    </head>
    <body>
        <?php
            require('apps/header.php');
            require('apps/content.php');
            require('apps/footer.php');
        ?>
        <script src="public/js/main.js"></script>
    </body>
</html>